---
functional:
  - Есть возможность зарегистрироваться с помощью Github
  - Есть возможность зарегистрироваться с помощью Discord
  - Есть возможность зарегистрироваться с помощью Email
  - При регистрации Nickname пользователя должен быть уникальным
  - При регистрации Email должна быть уникальной
  - Есть возможность авторизоваться с помощью Github
  - Есть возможность авторизоваться с помощью Discord
  - Есть возможность авторизоваться с помощью Email
  - Есть возможность попробовать игру без регистарации
  - Вызов может принять любой из зарегистрированных пользователе
  - Можно выборать игру с конкретным пользователем 
  - Можно выборать игру с ботом
  - Можно выбрать сложность решаемой задачи
  - Можно выборать язык программирования во время игры
  - Есть возможность видить поле противника во время игры
  - Есть возможность проверки решения задачи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Можно зайти без регистрации, если пользователь закрыл браузер, но не вышел из учетки
  - Нельзя изменять код соперника
  - Нельзя отправить приглашение самому себе
  - Можно отклонить приглашение


 
