---
functional:
  - Есть возможность зарегистрироваться с помощью Github
  - Есть возможность зарегистрироваться с помощью Discord
  - Есть возможность зарегистрироваться с помощью Email
  - При регистрации имея пользователя должно быть уникальным
  - При регистрации эл.почта должна быть уникальной
  - Есть возможность авторизоваться с помощью Github
  - Есть возможность авторизоваться с помощью Discord
  - Есть возможность авторизоваться с помощью Email
  - Есть возможность попробовать игру без регистарации
  - Можно выборать в соперники человека или бота
  - Можно выборать игру с конкретным или слчайным соперником
  - Можно выбрать сложность решаемой задачи
  - Можно выборать выборать язык программирования
  - Пользователь может увидить условия задачи после начала игры
  - Есть возможность видить поле противника во время игры
  - Есть возможность проверить решение
  - Рейтинг победителя увеличивается
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - 
  - 


 
